//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreakingAppCA2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherType
    {
        public int Id { get; set; }
        public string Weather { get; set; }
    
        public virtual Condition Condition { get; set; }
    }
}
